//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurseWorkAmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class rentLand
    {
        public int id { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<int> idLand { get; set; }
        public Nullable<System.DateTime> dateStard { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual land land { get; set; }
    }
}
